KnowledgePool/Controllers/DataViewerController.cs
using KnowledgePool.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Reflection;
using System.Reflection.Emit;

namespace KnowledgePool.Controllers
{
    public class DataViewerController : Controller
    {
        private readonly AllPrintingsContext _context;

        public DataViewerController(AllPrintingsContext context)
        {
            _context= context;
        }

        /// <summary>
        /// fetches creature stat data for 1 or more sets
        /// </summary>
        /// <param name="setIds">
        /// Set codes sent by the view
        /// </param>
        /// <param name="dataType">
        /// Choice of Average or Median
        /// </param>
        /// <param name="singleChart">
        /// Whether or not to display each set as a separate chart
        /// </param>
        /// <returns></returns>
        public ActionResult Index(List<string> setIds, string dataType, string singleChart = "false")
        {
            var isSingleChart = singleChart == "true";
            var isAverage = dataType?.Equals("average", StringComparison.OrdinalIgnoreCase) ?? true;

            //get set list for selection box
            var setListSelection = GetSetSelectionList();

            var setCodes = setIds;

            //if no set codes were passed in, get the most recent set
            if (!setCodes.Any())
                    setCodes.Add(_context.Sets
                        .Where(_ => _.Type == "expansion" || _.Type == "core" || _.Type == "masters")
                        .OrderByDescending(_ => _.ReleaseDate)
                        .Select(_ => _.Code)
                        .First());

            //source data for the charts
            var powerData = new Dictionary<string, string>();
            var toughnessData = new Dictionary<string, string>();
            var bubbleData = new Dictionary<string, string>();

            if (!isSingleChart)
            {
                foreach (var setCode in setCodes)
                {
                    //get cards in set then get creatures excluding outliers (0 or variable power and toughness)
                    var cards = _context.Cards.AsEnumerable().Where(_ => _.SetCode == setCode).DistinctBy(_ => _.Name).ToList();

                    var creatures = cards
                        .Where(_ =>
                        _.Type.Contains("creature", StringComparison.OrdinalIgnoreCase) && 
                        !_.Power.Contains("*") && 
                        !_.Toughness.Contains("*") && 
                        !(_.Power == "0" || _.Toughness == "0"));

                    //process creatures into data for the charts
                    var amd = GetAverageMedianDataByColor(creatures);

                    //put data into dictionaries depending on selection of average vs median
                    if (isAverage)
                    {
                        var averagePowers = new Dictionary<string, List<double>>(amd.Select(_ => new KeyValuePair<string, List<double>>
                            (
                                _.Key,
                                _.Value.PowerAverages.ToList()
                            )));

                        var averageToughnesses = new Dictionary<string, List<double>>(amd.Select(_ => new KeyValuePair<string, List<double>>
                            (
                                _.Key,
                                _.Value.ToughnessAverages.ToList()
                            )));

                        powerData.Add(setCode, GetAverageOrMedianJsonByColor(averagePowers, "Power", setCode));
                        toughnessData.Add(setCode, GetAverageOrMedianJsonByColor(averageToughnesses, "Toughness", setCode));
                    }

                    else
                    {
                        var medianPowers = new Dictionary<string, List<int>>(amd.Select(_ => new KeyValuePair<string, List<int>>
                        (
                            _.Key,
                            _.Value.PowerMedians.ToList()
                        )));

                        var medianToughnesses = new Dictionary<string, List<int>>(amd.Select(_ => new KeyValuePair<string, List<int>>
                        (
                            _.Key,
                            _.Value.ToughnessMedians.ToList()
                        )));

                        powerData.Add(setCode, GetAverageOrMedianJsonByColor(medianPowers, "Power", setCode));
                        toughnessData.Add(setCode, GetAverageOrMedianJsonByColor(medianToughnesses, "Toughness", setCode));
                    }

                    bubbleData.Add(setCode, GetBubbleJson(setCode));
                } 
            }

            //slightly different logic if only one set is selected
            else
            {
                var cards = _context.Cards.AsEnumerable().Where(_ => setCodes.Contains(_.SetCode)).DistinctBy(_ => _.Name).ToList();

                var creatures = cards
                    .Where(_ =>
                    _.Type.Contains("creature", StringComparison.OrdinalIgnoreCase) &&
                        !_.Power.Contains("*") &&
                        !_.Toughness.Contains("*") &&
                        !(_.Power == "0" || _.Toughness == "0"));

                var amd = GetAverageMedianDataBySet(creatures, setCodes);

                if (isAverage)
                {
                    var averagePowers = new Dictionary<string, List<double>>(amd.Select(_ => new KeyValuePair<string, List<double>>
                        (
                            _.Key,
                            _.Value.PowerAverages.ToList()
                        )));

                    var averageToughnesses = new Dictionary<string, List<double>>(amd.Select(_ => new KeyValuePair<string, List<double>>
                        (
                            _.Key,
                            _.Value.ToughnessAverages.ToList()
                        )));

                    powerData.Add("POWER", GetAverageOrMedianJsonBySet(averagePowers, "Power"));
                    toughnessData.Add("TOUGHNESS", GetAverageOrMedianJsonBySet(averageToughnesses, "Toughness"));
                }

                else
                {
                    var medianPowers = new Dictionary<string, List<int>>(amd.Select(_ => new KeyValuePair<string, List<int>>
                    (
                        _.Key,
                        _.Value.PowerMedians.ToList()
                    )));

                    var medianToughnesses = new Dictionary<string, List<int>>(amd.Select(_ => new KeyValuePair<string, List<int>>
                    (
                        _.Key,
                        _.Value.ToughnessMedians.ToList()
                    )));

                    powerData.Add("POWER", GetAverageOrMedianJsonBySet(medianPowers, "Power"));
                    toughnessData.Add("TOUGHNESS", GetAverageOrMedianJsonBySet(medianToughnesses, "Toughness"));
                }
            }


            //add data to views
            ViewBag.setList = setListSelection;

            ViewData["PowerData"] = powerData;
            ViewData["ToughnessData"] = toughnessData;
            ViewData["ScatterData"] = bubbleData;

            return View();
        }

        /// <summary>
        /// Fetches win rate data for a single set. Multi-set support to be implemented
        /// </summary>
        /// <param name="setIds">
        /// List of ids for sets to fetch. Will only contain a single set currently
        /// </param>
        /// <param name="excludeRares">
        /// whether or not to include rares in the calculations
        /// </param>
        /// <returns></returns>
        public ActionResult WinRateData(List<string> setIds, string excludeRares = "false")
        {
            //get list for set selection
            var setListSelection = GetSetSelectionList();

            //filter out sets that don't have win rate data in the database
            var setsWithWinRateData = _context.WinRates.Select(_ => _.Set).Distinct();
            setListSelection = setListSelection.Where(_ => setsWithWinRateData.Contains(_.Value)).ToList();

            //if no set selected get most recent set
            if (!setIds.Any())
                setIds.Add(_context.Sets
                    .Where(_ => (_.Type == "expansion" || _.Type == "core" || _.Type == "masters") && setsWithWinRateData.Contains(_.Code))
                    .OrderByDescending(_ => _.ReleaseDate)
                    .Select(_ => _.Code)
                    .First());

            //get win rates by mana value, text length, and color
            var wrByMv = GetWinrateJsonByManaValue(setIds.First(), excludeRares == "true");
            var wrByLength = GetWinrateJsonByTextLength(setIds.First(), excludeRares == "true");
            var wrByColor = GetWinrateJsonByColor(setIds.First(), excludeRares == "true");

            //add data to the viewbag, viewdata
            ViewBag.setList = setListSelection;

            ViewData["WinRateByMv"] = wrByMv;
            ViewData["WinRateByLength"] = wrByLength;
            ViewData["WinRateByColor"] = wrByColor;

            return View();
        }

        #region Helper Methods

        /// <summary>
        /// Gets average and median power and toughness for each set in setCodes, sorted by mana value
        /// </summary>
        /// <param name="creatures">
        /// list of all creatures
        /// </param>
        /// <param name="setCodes">
        /// list of sets to fetch data for
        /// </param>
        /// <returns>
        /// Dictionary where the key is the set code and the value is the associated data as defined by the custom object type AverageMedianData
        /// </returns>

KnowledgePool/Views/DataViewer/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model IEnumerable<KnowledgePool.Models.Card>

@using System.Linq
@using System.Text.Json

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Data Viewer";
}

@{
    var powerData = ViewData["PowerData"] as Dictionary<string, string>;
    var toughnessData = ViewData["ToughnessData"] as Dictionary<string, string>;
    var scatterData = ViewData["ScatterData"] as Dictionary<string, string>;
}

@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            @foreach (var d in powerData)
            {
                <text>
                    const powerDataChart_@d.Key = document.getElementById('@d.Key-powerData');
                    const powerChartJson_@d.Key = JSON.parse('@Html.Raw(d.Value)');
                    window['powerChart_@d.Key'] = new Chart(powerDataChart_@d.Key, powerChartJson_@d.Key);
                </text>
            }

            @foreach (var d in toughnessData)
            {
                <text>
                    const toughnessDataChart_@d.Key = document.getElementById('@d.Key-toughnessData');
                    const toughnessChartJson_@d.Key = JSON.parse('@Html.Raw(d.Value)');
                    window['toughnessChart_@d.Key'] = new Chart(toughnessDataChart_@d.Key, toughnessChartJson_@d.Key);
                </text>
            }

            @foreach (var d in scatterData)
            {
                <text>
                    const scatterDataChart_@d.Key = document.getElementById('@d.Key-scatterData');
                    const scatterChartJson_@d.Key = JSON.parse('@Html.Raw(d.Value)');
                    window['scatterChart_@d.Key'] = new Chart(scatterDataChart_@d.Key, scatterChartJson_@d.Key);
                </text>
            }

            //not functional, supposed to change min bubble size
            // scatterPlot.options.plugins.beforeDraw = chart => {
            //     chart.getDatasetMeta(0).data.forEach(v => {
            //         v.options.radius *= 5;
            //         v.options.hoverRadius = v.options.radius;
            //     });
            // }
            //
            //scatterPlot.update();

            loadSearchFromStorage();
        });

        //toggles visible datasets
        function toggleData(elem) {
            const length = elem.id.length
            const index = parseInt(elem.id[length - 1]);

            const hyphenIndex = elem.id.indexOf('-');
            const setCode = elem.id.substring(0, hyphenIndex);

            var plot;

            if (elem.id[length - 2] === "p") plot = window['powerChart_' + setCode];
            else if (elem.id[length - 2] === "t") plot = window['toughnessChart_' + setCode];
            else if (elem.id[length - 2] === "s") plot = window['scatterChart_' + setCode];

            const currentVisibility = plot.data.datasets[index].hidden;

            plot.data.datasets[index].hidden = !currentVisibility;
            plot.update();
        }

        //creates a button to display which sets are selected
        function addSearch(setInput) {
            const opts = Array.from(document.getElementById("setList").children);

            const searchedSets = document.getElementById('searchedSets');
            const existingButtons = Array.from(searchedSets.children, ({ textContent }) => textContent);

            if (!existingButtons.includes(setInput)) {
                opts.forEach((opt) => {
                    if (opt.value == setInput) {
                        const setButton = document.createElement('button');
                        setButton.innerText = setInput;
                        setButton.setAttribute('id', opt.textContent);
                        setButton.classList.add('set-button');

                        const hiddenInput = document.createElement('input');
                        hiddenInput.setAttribute('id', opt.textContent + "_input");
                        hiddenInput.setAttribute('value', opt.textContent);
                        hiddenInput.setAttribute('name', 'setIds');
                        hiddenInput.style = 'display:none';

                        setButton.addEventListener('click', function () {
                            searchedSets.removeChild(setButton);

                            const inputToRemove = document.getElementById(opt.textContent + "_input");
                            searchedSets.removeChild(inputToRemove);

                            saveSearchToStorage();
                        });

                        searchedSets.appendChild(setButton);
                        searchedSets.appendChild(hiddenInput);
                        saveSearchToStorage();

                        document.getElementById('set').value = '';

                    }
                });
            }
        }

        //save all searched terms to session storage
        function saveSearchToStorage() {
            const setButtons = document.querySelectorAll('.set-button');
            const sets = Array.from(setButtons).map(button => button.innerText);

            sessionStorage.setItem('searchSets', JSON.stringify(sets));
            console.log(sessionStorage.getItem('searchSets'));
        }

        //load all searched sets and create buttons
        function loadSearchFromStorage() {
            const storedSets = sessionStorage.getItem('searchSets');

            if (storedSets) {
                const sets = JSON.parse(storedSets);
                sets.forEach(set => addSearch(set));
            }

            console.log(storedSets);
        }
    </script>
}

<h2>Set Search</h2>
<p>
    @using (Html.BeginForm("Index", "DataViewer", FormMethod.Get))
    {
        <p>
            <label for="setList">Type the set name: </label>
            <input list="setList" id="set" oninput="addSearch(this.value)"/>
            <datalist id="setList" name="setList">
                @foreach (SelectListItem sli in ViewBag.setList)
                {
                    <option value=@sli.Text>@sli.Value</option>
                }
            </datalist>
            <br>

            <input type="radio" name="dataType" value="Average" checked="checked" /> Average
            <input type="radio" name="dataType" value="Median" /> Median
            <br>

            <input type="checkbox" name="singleChart" value="true"/> Display data on single chart 

            
            <div id="searchedSets">
                <!--sets will be added here as searched-->
            </div>
            <br>

            <input type="submit" value="Submit">
        </p>
    }
</p>

@foreach (var d in powerData)
{
    <canvas id="@d.Key-powerData"></canvas>

    @if (!Context.Request.QueryString.Value.Contains("singleChart=true"))
    {
        <div>
            <a id="@d.Key-p0" class="chart-action" onclick="toggleData(this)">Toggle White</a>
            <a id="@d.Key-p1" class="chart-action" onclick="toggleData(this)">Toggle Blue</a>
            <a id="@d.Key-p2" class="chart-action" onclick="toggleData(this)">Toggle Black</a>
            <a id="@d.Key-p3" class="chart-action" onclick="toggleData(this)">Toggle Red</a>
            <a id="@d.Key-p4" class="chart-action" onclick="toggleData(this)">Toggle Green</a>
            <a id="@d.Key-p5" class="chart-action" onclick="toggleData(this)">Toggle Gold</a>
            <a id="@d.Key-p6" class="chart-action" onclick="toggleData(this)">Toggle Colorless</a>
            <a id="@d.Key-p7" class="chart-action" onclick="toggleData(this)">Toggle Overall</a>
        </div>
    }
}

@foreach (var d in toughnessData)
{
    <canvas id="@d.Key-toughnessData"></canvas>

    @if (!Context.Request.QueryString.Value.Contains("singleChart=true"))
    {
        <div>
            <a id="@d.Key-t0" class="chart-action" onclick="toggleData(this)">Toggle White</a>
            <a id="@d.Key-t1" class="chart-action" onclick="toggleData(this)">Toggle Blue</a>
            <a id="@d.Key-t2" class="chart-action" onclick="toggleData(this)">Toggle Black</a>
            <a id="@d.Key-t3" class="chart-action" onclick="toggleData(this)">Toggle Red</a>
            <a id="@d.Key-t4" class="chart-action" onclick="toggleData(this)">Toggle Green</a>
            <a id="@d.Key-t5" class="chart-action" onclick="toggleData(this)">Toggle Gold</a>
            <a id="@d.Key-t6" class="chart-action" onclick="toggleData(this)">Toggle Colorless</a>
            <a id="@d.Key-t7" class="chart-action" onclick="toggleData(this)">Toggle Overall</a>
        </div>
    }
}

@foreach (var d in scatterData)
{
    <canvas id="@d.Key-scatterData"></canvas>

    @if (!Context.Request.QueryString.Value.Contains("singleChart=true"))
    {
        <div>
            <a id="@d.Key-s0" class="chart-action" onclick="toggleData(this)">Toggle White</a>
            <a id="@d.Key-s1" class="chart-action" onclick="toggleData(this)">Toggle Blue</a>
            <a id="@d.Key-s2" class="chart-action" onclick="toggleData(this)">Toggle Black</a>
            <a id="@d.Key-s3" class="chart-action" onclick="toggleData(this)">Toggle Red</a>
            <a id="@d.Key-s4" class="chart-action" onclick="toggleData(this)">Toggle Green</a>
            <a id="@d.Key-s5" class="chart-action" onclick="toggleData(this)">Toggle Gold</a>
            <a id="@d.Key-s6" class="chart-action" onclick="toggleData(this)">Toggle Colorless</a>
            <a id="@d.Key-s7" class="chart-action" onclick="toggleData(this)">Toggle Overall</a>
        </div>
    }
}

KnowledgePool/Views/DataViewer/WinRateData.cshtml
@{
    ViewData["Title"] = "Win Rate Data";
}

@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline"></script>
    <script type="text/javascript">
        //get chart data and create charts
        const wrByMvChart = document.getElementById('winRateByMv');
        const wrByMvChartJson = JSON.parse('@Html.Raw(ViewData["WinRateByMv"])');
        new Chart(wrByMvChart, wrByMvChartJson);

        const wrByLengthChart = document.getElementById('winRateByLength');
        const wrByLengthChartJson = JSON.parse('@Html.Raw(ViewData["WinRateByLength"])');
        new Chart(wrByLengthChart, wrByLengthChartJson);

        const wrByColorChart = document.getElementById('winRateByColor');
        const wrByColorChartJson = JSON.parse('@Html.Raw(ViewData["WinRateByColor"])');
        new Chart(wrByColorChart, wrByColorChartJson);

        //creates set search button when one is selected from the data list
        function addSearch(setInput) {
            //get all options from data list
            const opts = Array.from(document.getElementById("setList").children);

            //get all existing set buttons
            const searchedSets = document.getElementById('searchedSets');
            const existingButtons = Array.from(searchedSets.children, ({ textContent }) => textContent);

            //creates a button for a searched set if it doesn't already exist
            if (!existingButtons.includes(setInput)) {
                opts.forEach((opt) => {
                    if (opt.value == setInput) {
                        //create button
                        const setButton = document.createElement('button');
                        setButton.innerText = setInput;
                        setButton.setAttribute('id', opt.textContent);
                        setButton.classList.add('set-button');

                        //create hidden input so that we can send the value as a query string when the form is submitted
                        const hiddenInput = document.createElement('input');
                        hiddenInput.setAttribute('id', opt.textContent + "_input");
                        hiddenInput.setAttribute('value', opt.textContent);
                        hiddenInput.setAttribute('name', 'setIds');
                        hiddenInput.style = 'display:none';

                        //add even listener to delete the button when it is clicked
                        setButton.addEventListener('click', function () {
                            searchedSets.removeChild(setButton);

                            const inputToRemove = document.getElementById(opt.textContent + "_input");
                            searchedSets.removeChild(inputToRemove);

                            saveSearchToStorage();
                        });

                        //add the new elements to the div that contains them
                        searchedSets.appendChild(setButton);
                        searchedSets.appendChild(hiddenInput);
                        //saveSearchToStorage();

                        //reset the input for new set selection
                        document.getElementById('set').value = '';
                    }
                });
            }
        }
    </script>
}

<h2>Set Search</h2>
<p>
    @using (Html.BeginForm("WinRateData", "DataViewer", FormMethod.Get))
    {
    <p>
        <label for="setList">Type the set name: </label>
        <input list="setList" id="set" oninput="addSearch(this.value)" />
        <datalist id="setList" name="setList">
                @foreach (SelectListItem sli in ViewBag.setList)
                {
                    <option value=@sli.Text>@sli.Value</option>
                }
        </datalist>
        <br>

        <input type="checkbox" name="excludeRares" value="true" /> Exclude Rares and Mythics
        <br>

        <div id="searchedSets">
            <!--sets will be added here as searched-->
        </div>
        <br>

        <input type="submit" value="Submit">
    </p>
    }
</p>

<!--Canvases to hold the charts-->
<canvas id="winRateByMv"></canvas>

<canvas id="winRateByColor"></canvas>

<canvas id="winRateByLength"></canvas>