KnowledgePool/Models/WinRate.cs
using System.ComponentModel.DataAnnotations;

namespace KnowledgePool.Models
{
    public class WinRate
    {
        [Key]
        [Required]
        public string Uuid { get; set; } = null!;
        public string? Name { get; set; }
        public string? Set { get; set; }
        public string? Color { get; set; }
        public string? Rarity { get; set; }
        public decimal? OhWr { get; set; }
        public decimal? GdWr { get; set; }
        public decimal? GihWr { get; set; }
        public decimal? Iwd { get; set; }

    }
}

KnowledgePool/Controllers/WinRatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KnowledgePool.Models;
using KnowledgePool.Models.OtherModels;
using System.Text;
using SQLitePCL;

namespace KnowledgePool.Controllers
{
    public class WinRatesController : Controller
    {
        private readonly AllPrintingsContext _context;

        public WinRatesController(AllPrintingsContext context)
        {
            _context = context;
        }

        // GET: WinRates
        public async Task<IActionResult> Index()
        {
              return _context.WinRates != null ? 
                          View(await _context.WinRates.ToListAsync()) :
                          Problem("Entity set 'AllPrintingsContext.WinRates'  is null.");
        }

        // GET: WinRates/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.WinRates == null)
            {
                return NotFound();
            }

            var winRate = await _context.WinRates
                .FirstOrDefaultAsync(m => m.Uuid == id);
            if (winRate == null)
            {
                return NotFound();
            }

            return View(winRate);
        }

        // GET: WinRates/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WinRates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Uuid,Name,Set,Color,Rarity,OhWr,GdWr,GihWr,Iwd")] WinRate winRate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(winRate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(winRate);
        }

        // GET: WinRates/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.WinRates == null)
            {
                return NotFound();
            }

            var winRate = await _context.WinRates.FindAsync(id);
            if (winRate == null)
            {
                return NotFound();
            }
            return View(winRate);
        }

        // POST: WinRates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Uuid,Name,Set,Color,Rarity,OhWr,GdWr,GihWr,Iwd")] WinRate winRate)
        {
            if (id != winRate.Uuid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(winRate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WinRateExists(winRate.Uuid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(winRate);
        }

        // GET: WinRates/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.WinRates == null)
            {
                return NotFound();
            }

            var winRate = await _context.WinRates
                .FirstOrDefaultAsync(m => m.Uuid == id);
            if (winRate == null)
            {
                return NotFound();
            }

            return View(winRate);
        }

        // POST: WinRates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.WinRates == null)
            {
                return Problem("Entity set 'AllPrintingsContext.WinRates'  is null.");
            }
            var winRate = await _context.WinRates.FindAsync(id);
            if (winRate != null)
            {
                _context.WinRates.Remove(winRate);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WinRateExists(string id)
        {
          return (_context.WinRates?.Any(e => e.Uuid == id)).GetValueOrDefault();
        }

        //takes a csv file containing card win rates named [set code].csv and adds them to the database
        //to do: allow for updating the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadWinRates(FileUpload upload)
        {
            if (upload.File != null && upload.File.FileName.EndsWith(".csv"))
            {
                var setCode = upload.File.FileName.Substring(0, 3);

                var lines = new List<string>();
                using (var reader = new StreamReader(upload.File.OpenReadStream()))
                {
                    while (reader.Peek() >= 0)
                        lines.Add(reader.ReadLine());
                }

                var winRates = lines
                    .Skip(1)
                    .Select(_ => _.Split(new string[] { "\",\"" }, StringSplitOptions.None))
                    .Select(_ => new WinRate
                    {
                        Uuid = GetUuid(_[0].Substring(1), setCode),
                        Name = _[0].Substring(1),
                        Set = setCode,
                        Color = _[1],
                        Rarity = _[2],
                        OhWr = ConvertRate(_[11], 1),
                        GdWr = ConvertRate(_[13], 1),
                        GihWr = ConvertRate(_[15], 1),
                        Iwd = ConvertRate(_[18], 3),

                    })
                    .ToList();

                _context.WinRates.AddRange(winRates);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        //takes win rate given as string in the format xx.x% and converts it to a decimal
        public decimal? ConvertRate(string value, int endOfInput)
        {
            if (value.Length < 4) return null;

            else return Convert.ToDecimal(value.Substring(0, value.Length - endOfInput));
        }

        //get the id for a card with the given set, defaults to first id if the card doesn't have a set (cards on The List)
        public string GetUuid(string cardName, string setCode)
        {
            try
            {
                var bonusSheetCode = _context.Sets.Any(_ => _.ParentCode == setCode && _.Type == "masterpiece") ? _context.Sets.First(_ => _.ParentCode == setCode && _.Type == "masterpiece").Code : string.Empty;

                return 
                    _context.Cards.FirstOrDefault(_ => 
                    _.Name.StartsWith(cardName) && 
                    ((_.SetCode == setCode && _.PromoTypes == null) || 
                    _.SetCode == bonusSheetCode))
                    ?.Uuid 
                    ?? _context.Cards.First(_ => _.Name.StartsWith(cardName)).Uuid;

            }

            //TODO: handle exception
            catch (Exception e)
            {
                throw;
            }        
        }
    }
}

KnowledgePool/Views/WinRates/Create.cshtml
@model KnowledgePool.Models.WinRate

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WinRate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Uuid" class="control-label"></label>
                <input asp-for="Uuid" class="form-control" />
                <span asp-validation-for="Uuid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Set" class="control-label"></label>
                <input asp-for="Set" class="form-control" />
                <span asp-validation-for="Set" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rarity" class="control-label"></label>
                <input asp-for="Rarity" class="form-control" />
                <span asp-validation-for="Rarity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OhWr" class="control-label"></label>
                <input asp-for="OhWr" class="form-control" />
                <span asp-validation-for="OhWr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GdWr" class="control-label"></label>
                <input asp-for="GdWr" class="form-control" />
                <span asp-validation-for="GdWr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GihWr" class="control-label"></label>
                <input asp-for="GihWr" class="form-control" />
                <span asp-validation-for="GihWr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Iwd" class="control-label"></label>
                <input asp-for="Iwd" class="form-control" />
                <span asp-validation-for="Iwd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KnowledgePool/Views/WinRates/Delete.cshtml
@model KnowledgePool.Models.WinRate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WinRate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Set)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Set)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rarity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rarity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OhWr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OhWr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GdWr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GdWr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GihWr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GihWr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Iwd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Iwd)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Uuid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KnowledgePool/Views/WinRates/Details.cshtml
@model KnowledgePool.Models.WinRate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>WinRate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Set)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Set)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rarity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rarity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OhWr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OhWr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GdWr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GdWr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GihWr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GihWr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Iwd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Iwd)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Uuid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

KnowledgePool/Views/WinRates/Edit.cshtml
@model KnowledgePool.Models.WinRate

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>WinRate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Uuid" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Set" class="control-label"></label>
                <input asp-for="Set" class="form-control" />
                <span asp-validation-for="Set" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rarity" class="control-label"></label>
                <input asp-for="Rarity" class="form-control" />
                <span asp-validation-for="Rarity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OhWr" class="control-label"></label>
                <input asp-for="OhWr" class="form-control" />
                <span asp-validation-for="OhWr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GdWr" class="control-label"></label>
                <input asp-for="GdWr" class="form-control" />
                <span asp-validation-for="GdWr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GihWr" class="control-label"></label>
                <input asp-for="GihWr" class="form-control" />
                <span asp-validation-for="GihWr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Iwd" class="control-label"></label>
                <input asp-for="Iwd" class="form-control" />
                <span asp-validation-for="Iwd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KnowledgePool/Views/WinRates/Index.cshtml
@model IEnumerable<KnowledgePool.Models.WinRate>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1><br />

@using (Html.BeginForm("UploadWinRates", "WinRates", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    <h4>Upload Win Rates</h4><br />
    <input type="file" name="File"/><br />
    <input type="submit" value="Upload"/><br /><br />
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Set)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rarity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OhWr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GdWr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GihWr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Iwd)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Set)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rarity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OhWr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GdWr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GihWr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Iwd)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Uuid">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Uuid">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Uuid">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>